### ISSUE TITLE
yarn build for the UI is throwing "Uncaught ReferenceError: $RefreshReg$ is not defined"

### ISSUE THREAD

**Issue by TheNaman047** [MajorLift/typescript-fullstack-monorepo-starter#479]
Tried to build the project so it can be served via nginx from the server. But when doing `npx serve` on the build directory it gives following error:

```
Uncaught ReferenceError: $RefreshReg$ is not defined
    at 8157 (main-1dc0422de50588f86511.bundle.js?1dc0422de50588f86511:516:501361)
    at r (bootstrap:19:32)
    at _1 (main-1dc0422de50588f86511.bundle.js?1dc0422de50588f86511:784:12553)
    at main-1dc0422de50588f86511.bundle.js?1dc0422de50588f86511:784:12568
    at f (jsonp chunk loading:71:28)
    at main-1dc0422de50588f86511.bundle.js?1dc0422de50588f86511:1:1089
    at main-1dc0422de50588f86511.bundle.js?1dc0422de50588f86511:1:725
    at main-1dc0422de50588f86511.bundle.js?1dc0422de50588f86511:784:12582
    at main-1dc0422de50588f86511.bundle.js?1dc0422de50588f86511:784:12590
```

Node: v18.16.0
Yarn: 3.2.0

Tried various solutions for resolving webpack builds but didn't workout. 
https://stackoverflow.com/questions/66472945/referenceerror-refreshreg-is-not-defined

Thanks in advance.

**Comment by MajorLift** [comment]
Hi, thanks for reporting this. Could you provide a minimal test repo that reproduces the issue?

**Comment by TheNaman047** [comment]
I can but I don't think it's required. Let me explain.

Run the following command:
`yarn start`

This will execute the start script in the root package.json will do three things:
1. docker compose up
2. Build the Frontend
3. Start the Backend node server

Now, as per the code [here](https://github.com/MajorLift/typescript-fullstack-monorepo-starter/blob/d257bfc397dbf68b1b6f8b16603ed63d1c56e85c/server/src/main.ts#L33), the backend will server the frontend build. So opening `http://localhost:3000` will show a blank page.

Open the console and you'll see the error I mentioned.

Thanks for responding quickly. I have a project ongoing and am using this started code but unable to deploy it as I require the build version of the code. Though it works well in the dev mode.
